### ISSUE TITLE
5.6-rc5: 2001-Revert-serdev[...] unnecessary?

### ISSUE THREAD

**Issue by vattenapa** [jamlam/mbp2019-5.6-patches#1]
To start things off - thanks for the effort! This repo helped me loads with getting my 16,1 up and running.

Trying to compile 5.6-rc5, the mentioned patch no longer applies. Going through the changed code upstream it seems an addition has been made to detect apple machines and handle them properly [(link).](https://github.com/torvalds/linux/blob/2c523b344dfa65a3738e7039832044aa133c75fb/drivers/tty/serdev/core.c#L640)

With the patch removed, the kernel compiled & booted fine. I tested pairing with my phone and I was able to send and receive files. I didn't use bluetooth beforehand so I cannot tell if anything has changed, but everything works as expected on my end.

**Comment by jamlam** [comment]
Glad you found it useful :) 

That's good news on the Bluetooth fix, I'll get that one removed if it's no longer needed.

**Comment by jamlam** [comment]
Yep, seems to work absolutely fine without this now, removed.
